-- Lottery draw storage for Supabase
-- Run this in the Supabase SQL editor.

create table if not exists public.lottery_draws (
  id bigint generated by default as identity primary key,
  numbers jsonb not null,
  bonus_number integer not null,
  created_at timestamptz not null default now()
);

alter table public.lottery_draws
  enable row level security;

-- Allow anonymous/public inserts from the app.
drop policy if exists "Allow public insert lottery draws" on public.lottery_draws;
create policy "Allow public insert lottery draws"
  on public.lottery_draws
  for insert
  to anon
  with check (true);

-- Allow the app to read the most recent draws.
drop policy if exists "Allow public select lottery draws" on public.lottery_draws;
create policy "Allow public select lottery draws"
  on public.lottery_draws
  for select
  to anon
  using (true);

create index if not exists lottery_draws_created_at_idx
  on public.lottery_draws (created_at desc);
